language: c
notifications:
 irc:
  channels: "anathema.us.nu#anathema"
  use_notice: true
  skip_join: true
compiler:
 - clang
 - gcc
before_install:
 - sudo apt-get update -qq
install:
 - sudo apt-get install -y libgtk-3-dev liblua5.2-dev libjson-glib-dev
before_script:
 - mkdir build
 - cd build
env: NO_AT_BRIDGE=1
script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING=ON
 - make
 - cpack -G DEB
 - ctest -V
