language: c
notifications:
 irc:
  channels: "anathema.us.nu#anathema"
  use_notice: true
  skip_join: true
env:
 global:
  - secure: "C7cO92N/v374viYwfnVQo75xeDRXO/3S//OruK5BsafWPotaRn1fHV8teLctVE5a8DOvLZVv3YcY0Hzf03KHvxHJsEuHyJhTePsdn2Ldx3RaQH/fNAvqH6uugR+1cz1p33ex+5Em9I+dgXrdDTj5XfJLxrBxfk0swvYnW4GyxD4="
addons:
 coverity_scan:
  project:
   name: "pjanouch/logdiag"
   description: "Schematic editor"
  notification_email: p.janouch@gmail.com
  build_command_prepend: "cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON"
  build_command: "make"
  branch_pattern: coverity_scan
compiler:
 - clang
 - gcc
before_install:
 - sudo apt-get update -qq
 - export DISPLAY=:99.0
 - export NO_AT_BRIDGE=1
 - sh -e /etc/init.d/xvfb start
install:
 - sudo apt-get install -y libgtk-3-dev liblua5.2-dev libjson-glib-dev
before_script:
 - mkdir build
 - cd build
script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING=ON
 - make
 - cpack -G DEB
 - ctest -V
